kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1
commonLabels:
  app.kubernetes.io/part-of: forgerock
images:
- name: git-server
  newName: gcr.io/forgeops-public/git-server
- name: .*am
  newName: gcr.io/forgeops-public/am
  newTag: dev
- name: .*amster.*
  newName: gcr.io/forgerock-io/amster/pit1
  newTag: 7.2.0-latest-postcommit
- name: .*idm
  newName: gcr.io/forgeops-public/idm
  newTag: dev
- name: .*ds-cts.*
  newName: gcr.io/forgeops-public/ds-cts
  newTag: dev
- name: .*ds-idrepo.*
  newName: gcr.io/forgeops-public/ds-idrepo
  newTag: dev
- name: .*ig.*
  newName: gcr.io/forgeops-public/ig
  newTag: dev
