apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-idrepo
spec:
  template:
    spec:
      subdomain: ds-idrepo-us
      containers:
        - name: ds
          env:
            - name: DS_BOOTSTRAP_REPLICATION_SERVERS
              value: ds-idrepo-0.ds-idrepo-us.multi-cluster.svc.cluster.local:8989,ds-idrepo-0.ds-idrepo-europe.multi-cluster.svc.cluster.local:8989
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
      initContainers:
        - name: initialize
          imagePullPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi