apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-cts
spec:
  template:
    spec:
      subdomain: ds-cts-europe
      containers:
        - name: ds
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
      initContainers:
        - name: initialize
          imagePullPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi