# Deploys ds-idrepo and ds-cts only. Used by PIT/Perf teams.
resources:
  - ../../base/kustomizeConfig
  - ../../base/ds/cts
  - ../../base/ds/idrepo

patches:
  - path: base.yaml
  - path: ds-idrepo-old.yaml

